"use client";
import {useState} from "react";
import {ArrowDownRight,ArrowUpRight,Check,Menu,Plus,ShoppingBag} from "lucide-react";
const works=[
{id:1,title:"Untamed",artist:"Sina Soleimani",place:"Tehran",medium:"Painting",size:"Dimensions on request",edition:"Original · 1 of 1",price:2800,image:"/art/sina-untamed.webp",kind:"PAINTING"},
{id:2,title:"Under the Skin",artist:"Sina Soleimani",place:"Tehran",medium:"Painting",size:"Dimensions on request",edition:"Original · 1 of 1",price:3900,image:"/art/sina-under-skin.webp",kind:"PAINTING"},
{id:3,title:"Icarus",artist:"Sina Soleimani",place:"Tehran",medium:"Sculpture · metal",size:"Dimensions on request",edition:"Unique work",price:6800,image:"/art/sina-icarus.webp",kind:"SCULPTURE"}];
const frames=[{name:"Unframed",color:"transparent",cost:0},{name:"Black oak",color:"#171717",cost:240},{name:"Natural oak",color:"#aa8054",cost:290},{name:"Brushed gold",color:"#b58b3d",cost:360}];
export default function Home(){const[selected,setSelected]=useState(works[0]);const[frame,setFrame]=useState(frames[1]);const[wall,setWall]=useState("#d6d0c5");const[cart,setCart]=useState<number[]>([]);const[menu,setMenu]=useState(false);const add=(id:number)=>setCart(c=>c.includes(id)?c:[...c,id]);return <main>
<header className="nav"><button className="menu-btn" onClick={()=>setMenu(!menu)} aria-label="Open menu"><Menu size={20}/></button><a className="brand" href="#top"><span>SETAI</span><i>ART</i></a><nav className={menu?"links open":"links"}><a href="#collection" onClick={()=>setMenu(false)}>Collection</a><a href="#artists" onClick={()=>setMenu(false)}>Artists</a><a href="#atelier" onClick={()=>setMenu(false)}>Private view</a></nav><button className="bag" aria-label={`Shopping bag, ${cart.length} items`}><ShoppingBag size={18}/><b>{cart.length}</b></button></header>
<section className="hero" id="top"><div className="hero-copy"><span className="eyebrow">CURATED BETWEEN EAST & NORTH · 2026</span><h1>Art with<br/><em>another memory.</em></h1><p>Persian voices. Scandinavian rooms. Singular works selected for collectors who prefer substance over spectacle.</p><a className="text-link" href="#collection">Discover the collection <ArrowDownRight size={18}/></a></div><div className="hero-art"><div className="arch"><img src="/art/sina-untamed-iii.webp" alt="Untamed III by Sina Soleimani"/></div><div className="hero-note"><span>01</span><p>Untamed III<br/><i>Sina Soleimani</i></p></div><span className="persian">هنر، خاطره‌ی دیگر</span></div></section>
<section className="marquee"><div>PAINTINGS <i>✦</i> SCULPTURE <i>✦</i> COLLECTIBLE DESIGN <i>✦</i> ORIGINAL WORKS <i>✦</i> PAINTINGS <i>✦</i> SCULPTURE</div></section>
<section className="collection" id="collection"><div className="section-head"><div><span className="eyebrow">THE CURRENT EDIT</span><h2>Selected works</h2></div><p>Each work is sourced directly from the artist and accompanied by a signed certificate of authenticity.</p></div><div className="art-grid">{works.map((work,index)=><article className={`art-card card-${index+1}`} key={work.id}><button className="art-image" onClick={()=>{setSelected(work);document.getElementById("atelier")?.scrollIntoView({behavior:"smooth"})}}><img src={work.image} alt={`${work.title} by ${work.artist}`}/><span>{work.kind}</span></button><div className="art-meta"><div><h3>{work.title}</h3><p>{work.artist} · {work.place}</p></div><b>€{work.price.toLocaleString()}</b></div><button className="quick" onClick={()=>add(work.id)}>{cart.includes(work.id)?<><Check size={16}/> Reserved</>:<><Plus size={16}/> Add to enquiry</>}</button></article>)}</div></section>
<section className="atelier" id="atelier"><div className="room" style={{background:wall}}><span className="room-label">VIEW IN YOUR SPACE</span><div className={`frame ${frame.name==="Unframed"?"bare":""}`} style={{borderColor:frame.color}}><img src={selected.image} alt="Artwork preview"/></div><div className="bench"/></div><div className="config"><span className="eyebrow">COLLECTOR&apos;S VIEW</span><h2>{selected.title}</h2><p className="artist">{selected.artist}</p><dl><div><dt>Medium</dt><dd>{selected.medium}</dd></div><div><dt>Dimensions</dt><dd>{selected.size}</dd></div><div><dt>Availability</dt><dd>{selected.edition}</dd></div></dl>{selected.kind==="PAINTING"&&<><label>Choose a frame</label><div className="frame-options">{frames.map(f=><button key={f.name} className={f.name===frame.name?"active":""} onClick={()=>setFrame(f)}><i style={{background:f.color}}/>{f.name}{f.cost>0&&<small>+€{f.cost}</small>}</button>)}</div></>}<label>Wall colour</label><div className="swatches">{["#d6d0c5","#e6e0d6","#9ca39b","#354752","#772f34"].map(c=><button aria-label={`Wall color ${c}`} key={c} style={{background:c}} className={c===wall?"active":""} onClick={()=>setWall(c)}/>)}</div><div className="buy-row"><div><small>Artwork {frame.cost?"+ frame":""}</small><strong>€{(selected.price+(selected.kind==="PAINTING"?frame.cost:0)).toLocaleString()}</strong></div><button onClick={()=>add(selected.id)}>{cart.includes(selected.id)?"Enquiry added":"Acquire this work"}<ArrowUpRight size={18}/></button></div><p className="delivery"><Check size={14}/> Insured delivery to Scandinavia, usually within 4–8 weeks.</p></div></section>
<section className="artists" id="artists"><span className="eyebrow">MEET THE ARTISTS</span><h2>Many practices.<br/><em>One living heritage.</em></h2><a className="artist-row" href="/art/artists/sina-soleimani"><span>01</span><h3>Sina Soleimani</h3><p>Painting · sculpture · artistic research</p><ArrowUpRight/></a></section>
<footer><div className="footer-mark">SETAI <i>ART</i></div><p>Curated Persian art for Scandinavian collectors.</p><div><a href="mailto:art@setai.no">art@setai.no</a><a href="#top">Instagram</a><a href="#top">Terms</a></div><small>© 2026 Setai Art · Oslo</small><span lang="fa" dir="rtl">با عشق، از ایران تا اسکاندیناوی</span></footer></main>}
