import {ArrowLeft,ArrowUpRight} from "lucide-react";

const selected=[
{title:"Untamed",type:"Painting",price:"€2,800",image:"/art/sina-untamed.webp"},
{title:"Untamed III",type:"Painting",price:"€3,400",image:"/art/sina-untamed-iii.webp"},
{title:"Under the Skin",type:"Painting",price:"€3,900",image:"/art/sina-under-skin.webp"},
{title:"Trilogy",type:"Painting",price:"€4,200",image:"/art/sina-trilogy.webp"},
{title:"Suspended Between Control and Flight",type:"Painting",price:"€4,600",image:"/art/sina-suspended.webp"},
{title:"Icarus",type:"Sculpture · metal",price:"€6,800",image:"/art/sina-icarus.webp"},
];

export default function SinaSoleimani(){return <main className="profile-page">
<header className="profile-nav"><a href="/art/"><ArrowLeft size={17}/> Setai Art</a><span>ARTIST 01 / TEHRAN</span><a href="mailto:art@setai.no">Private enquiry <ArrowUpRight size={16}/></a></header>
<section className="profile-hero"><div className="portrait"><img src="/art/sina-portrait.jpg" alt="Artist Sina Soleimani"/><span lang="fa" dir="rtl">سینا سلیمانی</span></div><div className="profile-title"><span className="eyebrow">MULTIDISCIPLINARY ARTIST & EDUCATOR</span><h1>Sina<br/><em>Soleimani</em></h1><p>His paintings and sculptures move between observed reality, myth and psychological tension—often placing the human figure inside narratives that feel both intimate and unsettled.</p><a href="#works">View selected works <ArrowUpRight size={17}/></a></div></section>
<section className="profile-story"><aside><span>BASED IN</span><strong>Tehran, Iran</strong><span>DISCIPLINES</span><strong>Painting, sculpture,<br/>caricature & design</strong><span>REPRESENTATION</span><strong>Setai Art · Scandinavia</strong></aside><article><span className="eyebrow">THE ARTIST</span><h2>Stories held<br/>inside the figure.</h2><p>Soleimani is a multidisciplinary artist whose practice is anchored in artistic research and narrative. Across painting, sculpture and design, the body becomes a place where private experience meets social memory.</p><p>He holds an M.A. in Painting from the University of Art, Tehran, and degrees in Industrial Design from Tehran and Design from the Yerevan Academy of Fine Arts. His background gives the work an unusual balance: painterly instinct shaped by an understanding of structure, object and space.</p><p>His work has appeared in solo and group exhibitions in Iran, including the Contemporary Artist Grand Prize Exhibition at Artists’ House, Tehran. He has also created public murals in Tehran and Yerevan and worked as a painter and sculptor on the Middle East Animation Project within the Global Peace Project.</p></article></section>
<section className="profile-works" id="works"><div className="works-head"><div><span className="eyebrow">CURATOR'S SELECTION</span><h2>Available works</h2></div><p>Indicative launch prices in EUR. Final price, dimensions, framing and availability are confirmed in the collector enquiry.</p></div><div className="works-grid">{selected.map((w,i)=><article key={w.title} className={i===3?"wide":""}><div className="work-img"><img src={w.image} alt={`${w.title} by Sina Soleimani`}/><span>0{i+1}</span></div><div><h3>{w.title}</h3><p>{w.type}</p><strong>{w.price}</strong></div></article>)}</div></section>
<section className="profile-career"><span className="eyebrow">SELECTED MILESTONES</span><div><b>2024—NOW</b><p>Fine arts educator, Tehran</p></div><div><b>2023</b><p>M.A. Painting, University of Art, Tehran · Contemporary Artist Grand Prize Exhibition</p></div><div><b>2022</b><p>Group exhibition, Sarai Pour Gallery, Khur</p></div><div><b>2008</b><p>Honorable Diploma, Election Caricature Competition, Romania</p></div><div><b>2005</b><p>Solo exhibition, Mat Gallery, Tehran</p></div></section>
<section className="profile-cta"><span lang="fa" dir="rtl">اثری برای زندگی با آن</span><h2>Interested in a work?</h2><p>We arrange a private video viewing, condition details, certificate of authenticity and insured delivery to Scandinavia within approximately 4–8 weeks.</p><a href="mailto:art@setai.no?subject=Sina%20Soleimani%20artwork%20enquiry">Request a private viewing <ArrowUpRight/></a></section>
<footer className="profile-footer"><a href="/">SETAI <i>ART</i></a><small>© 2026 Setai Art · Oslo</small></footer>
</main>}
